services:

  mysql_maestro:
    image: mysql:8
    container_name: mysql_maestro

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mundial

    ports:
      - "3306:3306"

    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=mundial

    volumes:
      - ./mysql/maestro.cnf:/etc/mysql/conf.d/maestro.cnf:ro

  mysql_esclavo:
    image: mysql:8
    container_name: mysql_esclavo

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mundial

    ports:
      - "3307:3306"

    command: --server-id=2 --relay-log=relay-log --read-only=1

    depends_on:
      - mysql_maestro

    volumes:
      - ./mysql/esclavo.cnf:/etc/mysql/conf.d/esclavo.cnf:ro
